name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main
      - dev-pankaj

jobs:
  ftp-deploy:
    name: 🚀 Deploy Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./        # folder with your website files
          server-dir: /public_html/  # or subfolder for your site
          dangerous-clean-slate: false  # WARNING: deletes old files first